Added  observability chart installation
rancher/observability-e2e pull request #1
Opened 2024-09-24 09:46 UTC by deepakpunia-suse

2024-09-24 09:46 UTC, deepakpunia-suse commented
/assign @pankajsqe

2024-10-01 11:27 UTC, pankajsqe commented on tests/e2e/installations_test.go
> +		clientWithSession, err := client.WithSession(sess)
1. we can use code reusability in installation.go by creating a new client session once and utilizing it for all three tests.
```
client, err = rancher.NewClient("", testSession)
	Expect(err).NotTo(HaveOccurred())
```

2024-10-01 11:29 UTC, pankajsqe requested changes

2024-10-01 11:29 UTC, pankajsqe commented on tests/e2e/suite_test.go
> +	RunSpecs(t, "Monitoring End-To-End Test Suite")
2. suite.go should have description "Observability End-To-End Test Suite" instead of "Monitoring End-To-End Test Suite"

`RunSpecs(t, "Monitoring End-To-End Test Suite")`

2024-10-01 11:29 UTC, pankajsqe commented on tests/e2e/installations_test.go
> +		clientWithSession, err := client.WithSession(sess)
1. we can use code reusability in installation.go by creating a new client session once and utilizing it for all three tests.
```
client, err = rancher.NewClient("", testSession)
	Expect(err).NotTo(HaveOccurred())
```

2024-10-01 13:15 UTC, deepakpunia-suse commented on tests/e2e/installations_test.go
> +		clientWithSession, err := client.WithSession(sess)
Thanks, Fixed and moved under `BeforeEach` part, Will be executed only 1 time.
https://github.com/rancher/observability-e2e/pull/1/files#diff-b56287723dd44011738099eb681438bb60b1c254025392f586cc682bdc86388eR34

2024-10-01 13:16 UTC, deepakpunia-suse commented on tests/e2e/suite_test.go
> +	RunSpecs(t, "Monitoring End-To-End Test Suite")
Updated, Thank you :+1:

2024-10-01 14:20 UTC, pankajsqe approved these changes
LGTM

2024-10-01 14:26 UTC, merged