Enhance Testing and Codebase with Label-based E2E Logs, Chart Polling, and Dependency Cleanup
rancher/observability-e2e pull request #2
Opened 2024-10-10 09:43 UTC by deepakpunia-suse

Introduced label-based logging for executing end-to-end tests.
Added wait.poll for improved chart handling.
Removed dependencies and refactored code for better maintainability and performance.

2024-10-10 09:46 UTC, deepakpunia-suse commented
/assign @edangovsuse

2024-10-18 06:39 UTC, pankajsqe requested changes

2024-10-18 06:39 UTC, pankajsqe commented on tests/e2e/installations_test.go
> +	It("Install monitoring chart", Label("LEVEL0", "monitoring", "Author:dpunia"), func() {
we dont require any "author" lable in test as there wont be any usecase to run tests that are author specific.

2024-10-18 06:39 UTC, pankajsqe commented on tests/e2e/installations_test.go
> +	It("Install Alerting chart", Label("LEVEL0", "alerting", "Author:dpunia"), func() {
we dont require any "author" lable in test as there wont be any usecase to run tests that are author specific.

2024-10-18 09:07 UTC, deepakpunia-suse commented on tests/e2e/installations_test.go
> +	It("Install monitoring chart", Label("LEVEL0", "monitoring", "Author:dpunia"), func() {
Fixed

2024-10-18 09:54 UTC, pankajsqe approved these changes
LGTM

2024-10-18 11:57 UTC, merged